CREATE TABLE IF NOT EXISTS users (
    user_id TEXT PRIMARY KEY UNIQUE NOT NULL,
    username TEXT NOT NULL,
    team_name TEXT,
    FOREIGN KEY (team_name) REFERENCES teams(team_name) ON DELETE SET NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
)

CREATE INDEX IF NOT EXISTS idx_team_name ON users (team_name);
CREATE INDEX IF NOT EXISTS idx_is_active ON users (is_active);

CREATE TABLE IF NOT EXISTS teams (
    team_name TEXT PRIMARY KEY UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
)



